import { Product, ProductStatus } from "./types";

export const PRODUCTS_MOCK: Product[] = [
  {
    id: "mbp14m3pro",
    name: 'MacBook Pro 14"',
    sku: "MBP14M3PRO",
    description: "Laptop z procesorem M3 Pro, 18 GB RAM, 512 GB SSD.",
    category: "Komputery",
    grossPrice: 9999,
    currency: "PLN",
    status: ProductStatus.AVAILABLE,
    stockQuantity: null,
  },
  {
    id: "sgs24u256",
    name: "Galaxy S24 Ultra",
    sku: "SGS24U256",
    description: "Smartfon z ekranem 6,8 cala i 256 GB pamięci.",
    category: "Telefony",
    grossPrice: 6299,
    currency: "PLN",
    status: ProductStatus.AVAILABLE,
    stockQuantity: 45,
  },
  {
    id: "snwh1000xm5",
    name: "Sony WH-1000XM5",
    sku: "SNWH1000XM5",
    description: "Bezprzewodowe słuchawki z aktywną redukcją szumów.",
    category: "RTV",
    grossPrice: 1599,
    currency: "PLN",
    status: ProductStatus.AVAILABLE,
    stockQuantity: null,
  },
  {
    id: "bswau28p40",
    name: "Bosch Serie 6 WAU28P40",
    sku: "BSWAU28P40",
    description: "Pralka ładowana od frontu, 9 kg, klasa A.",
    category: "AGD",
    grossPrice: 3299,
    currency: "PLN",
    status: ProductStatus.UNAVAILABLE,
    stockQuantity: 0,
  },
  {
    id: "xmsb8blk",
    name: "Xiaomi Smart Band 8",
    sku: "XMSB8BLK",
    description: "Opaska sportowa z pomiarem tętna i SpO2.",
    category: "Akcesoria",
    grossPrice: 179,
    currency: "PLN",
    status: ProductStatus.AVAILABLE,
    stockQuantity: null,
  },
  {
    id: "lgoled55c4",
    name: "LG OLED55C4",
    sku: "LGOLED55C4",
    description: "Telewizor OLED evo 55 cali, 4K, 144 Hz.",
    category: "RTV",
    grossPrice: 4999,
    currency: "PLN",
    status: ProductStatus.AVAILABLE,
    stockQuantity: 12,
  },
  {
    id: "dellu2723qe",
    name: "Dell UltraSharp U2723QE",
    sku: "DELLU2723QE",
    description: "Monitor 27 cali 4K IPS Black z hubem USB-C.",
    category: "Komputery",
    grossPrice: 2999,
    currency: "PLN",
    status: ProductStatus.AVAILABLE,
    stockQuantity: 10,
  },
];
